// <auto-generated />
namespace Projeto.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DataEF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataEF));
        
        string IMigrationMetadata.Id
        {
            get { return "201712242200219_Data-EF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
