// <auto-generated />
namespace Easy.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EntitiesValues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntitiesValues));
        
        string IMigrationMetadata.Id
        {
            get { return "201712312057073_Entities-Values"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
